kind: pipeline
name: default

steps:
- name: publish
  image:  plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_password: docker_password
    repo: ramzit27/webserver
    autotag: true
    dockerfile: Dockerfile
    env:
      PLUGIN_DEBUG: "true"  
